// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiFormsIdData, DeleteApiFormsIdErrors, DeleteApiFormsIdResponses, GetApiAdminFormsData, GetApiAdminFormsErrors, GetApiAdminFormsResponses, GetApiFormsIdData, GetApiFormsIdErrors, GetApiFormsIdResponses, GetApiFormsResponsesData, GetApiFormsResponsesErrors, GetApiFormsResponsesResponses, GetApiHealthData, GetApiHealthResponses, GetAuthGoogleCallbackData, GetAuthGoogleCallbackErrors, GetAuthGoogleData, GetPublicFormBySlugData, GetPublicFormBySlugErrors, GetPublicFormBySlugResponses, PatchApiFormsPublishData, PatchApiFormsPublishResponses, PostApiFormsData, PostApiFormsErrors, PostApiFormsResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PutApiFormsIdData, PutApiFormsIdErrors, PutApiFormsIdResponses, RestoreApiFormsIdData, RestoreApiFormsIdErrors, RestoreApiFormsIdResponses, SubmitPublicFormData, SubmitPublicFormErrors, SubmitPublicFormResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Listar Formulários
 */
export const getApiAdminForms = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminFormsData, ThrowOnError>): RequestResult<GetApiAdminFormsResponses, GetApiAdminFormsErrors, ThrowOnError> => (options?.client ?? client).get<GetApiAdminFormsResponses, GetApiAdminFormsErrors, ThrowOnError>({ url: '/api/admin/forms', ...options });

/**
 * Alternar Publicação
 */
export const patchApiFormsPublish = <ThrowOnError extends boolean = false>(options: Options<PatchApiFormsPublishData, ThrowOnError>): RequestResult<PatchApiFormsPublishResponses, unknown, ThrowOnError> => (options.client ?? client).patch<PatchApiFormsPublishResponses, unknown, ThrowOnError>({
    url: '/api/admin/forms/{id}/publish',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Criar formulário
 *
 * Cria um novo formulário com os campos especificados
 */
export const postApiForms = <ThrowOnError extends boolean = false>(options: Options<PostApiFormsData, ThrowOnError>): RequestResult<PostApiFormsResponses, PostApiFormsErrors, ThrowOnError> => (options.client ?? client).post<PostApiFormsResponses, PostApiFormsErrors, ThrowOnError>({
    url: '/api/forms',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Excluir Formulário
 *
 * Remove o formulário e suas dependências pelo ID
 */
export const deleteApiFormsId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiFormsIdData, ThrowOnError>): RequestResult<DeleteApiFormsIdResponses, DeleteApiFormsIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteApiFormsIdResponses, DeleteApiFormsIdErrors, ThrowOnError>({ url: '/api/forms/{id}', ...options });

/**
 * Buscar Formulário por ID
 *
 * Retorna a estrutura completa do formulário e seus campos para edição
 */
export const getApiFormsId = <ThrowOnError extends boolean = false>(options: Options<GetApiFormsIdData, ThrowOnError>): RequestResult<GetApiFormsIdResponses, GetApiFormsIdErrors, ThrowOnError> => (options.client ?? client).get<GetApiFormsIdResponses, GetApiFormsIdErrors, ThrowOnError>({ url: '/api/forms/{id}', ...options });

/**
 * Atualizar Formulário
 *
 * Atualiza título, descrição, slug e reescreve os campos do formulário
 */
export const putApiFormsId = <ThrowOnError extends boolean = false>(options: Options<PutApiFormsIdData, ThrowOnError>): RequestResult<PutApiFormsIdResponses, PutApiFormsIdErrors, ThrowOnError> => (options.client ?? client).put<PutApiFormsIdResponses, PutApiFormsIdErrors, ThrowOnError>({
    url: '/api/forms/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Listar Respostas do Formulário
 */
export const getApiFormsResponses = <ThrowOnError extends boolean = false>(options: Options<GetApiFormsResponsesData, ThrowOnError>): RequestResult<GetApiFormsResponsesResponses, GetApiFormsResponsesErrors, ThrowOnError> => (options.client ?? client).get<GetApiFormsResponsesResponses, GetApiFormsResponsesErrors, ThrowOnError>({ url: '/api/forms/{id}/responses', ...options });

/**
 * Restaurar Formulário
 */
export const restoreApiFormsId = <ThrowOnError extends boolean = false>(options: Options<RestoreApiFormsIdData, ThrowOnError>): RequestResult<RestoreApiFormsIdResponses, RestoreApiFormsIdErrors, ThrowOnError> => (options.client ?? client).patch<RestoreApiFormsIdResponses, RestoreApiFormsIdErrors, ThrowOnError>({ url: '/api/forms/{id}/restore', ...options });

/**
 * Health Check
 *
 * Retorna OK se a aplicação estiver respondendo
 */
export const getApiHealth = <ThrowOnError extends boolean = false>(options?: Options<GetApiHealthData, ThrowOnError>): RequestResult<GetApiHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Login com Google
 *
 * Inicia o fluxo de autenticação OAuth2 gerando o cookie de estado
 */
export const getAuthGoogle = <ThrowOnError extends boolean = false>(options?: Options<GetAuthGoogleData, ThrowOnError>): RequestResult<unknown, unknown, ThrowOnError> => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/auth/google', ...options });

/**
 * Callback do Google OAuth2
 *
 * Processa o retorno do OAuth2, valida o estado via Cookie e redireciona ao Frontend
 */
export const getAuthGoogleCallback = <ThrowOnError extends boolean = false>(options?: Options<GetAuthGoogleCallbackData, ThrowOnError>): RequestResult<unknown, GetAuthGoogleCallbackErrors, ThrowOnError> => (options?.client ?? client).get<unknown, GetAuthGoogleCallbackErrors, ThrowOnError>({ url: '/auth/google/callback', ...options });

/**
 * Login com Email e Senha
 *
 * Realiza autenticação simples e retorna um JWT fictício
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>): RequestResult<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError> => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Buscar Formulário Público
 *
 * Retorna o formulário e seus campos visíveis usando o slug único
 */
export const getPublicFormBySlug = <ThrowOnError extends boolean = false>(options: Options<GetPublicFormBySlugData, ThrowOnError>): RequestResult<GetPublicFormBySlugResponses, GetPublicFormBySlugErrors, ThrowOnError> => (options.client ?? client).get<GetPublicFormBySlugResponses, GetPublicFormBySlugErrors, ThrowOnError>({ url: '/f/{slug}', ...options });

/**
 * Submeter Resposta de Formulário
 *
 * Recebe um objeto JSON com os pares de pergunta/resposta e persiste no banco
 */
export const submitPublicForm = <ThrowOnError extends boolean = false>(options: Options<SubmitPublicFormData, ThrowOnError>): RequestResult<SubmitPublicFormResponses, SubmitPublicFormErrors, ThrowOnError> => (options.client ?? client).post<SubmitPublicFormResponses, SubmitPublicFormErrors, ThrowOnError>({
    url: '/f/{slug}/submit',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
