// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:8080/' | (string & {});
};

export type BackendInternalModelAuthResponse = {
    token?: string;
};

export type BackendInternalModelForm = {
    createdAt?: string;
    description?: string;
    fields?: Array<BackendInternalModelFormField>;
    id?: string;
    published?: boolean;
    responses?: Array<BackendInternalModelFormResponse>;
    slug?: string;
    title?: string;
    updatedAt?: string;
    userId?: string;
};

export type BackendInternalModelFormField = {
    createdAt?: string;
    fieldType?: string;
    formId?: string;
    id?: string;
    label?: string;
    /**
     * @swaggertype object
     */
    options?: Array<number>;
    orderIndex?: number;
    required?: boolean;
    updatedAt?: string;
};

export type BackendInternalModelFormResponse = {
    /**
     * @swaggertype object
     */
    answers?: Array<number>;
    formId?: string;
    id?: string;
    submittedAt?: string;
};

export type BackendInternalModelFormSummary = {
    createdAt?: string;
    description?: string;
    id?: string;
    publicUrl?: string;
    published?: boolean;
    responsesCount?: number;
    title?: string;
};

export type BackendInternalModelLoginRequest = {
    email?: string;
    password?: string;
};

export type InternalHandlerCreateFormRequest = {
    description?: string;
    fields?: Array<BackendInternalModelFormField>;
    published?: boolean;
    slug?: string;
    title?: string;
    userId?: string;
};

export type GetApiAdminFormsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Exibir excluídos
         */
        deleted?: boolean;
    };
    url: '/api/admin/forms';
};

export type GetApiAdminFormsErrors = {
    /**
     * Erro ao buscar formulários
     */
    500: string;
};

export type GetApiAdminFormsError = GetApiAdminFormsErrors[keyof GetApiAdminFormsErrors];

export type GetApiAdminFormsResponses = {
    /**
     * OK
     */
    200: Array<BackendInternalModelFormSummary>;
};

export type GetApiAdminFormsResponse = GetApiAdminFormsResponses[keyof GetApiAdminFormsResponses];

export type PatchApiFormsPublishData = {
    /**
     * Payload contendo {published: bool}
     */
    body: {
        [key: string]: boolean;
    };
    path: {
        /**
         * ID do Formulário
         */
        id: string;
    };
    query?: never;
    url: '/api/admin/forms/{id}/publish';
};

export type PatchApiFormsPublishResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PatchApiFormsPublishResponse = PatchApiFormsPublishResponses[keyof PatchApiFormsPublishResponses];

export type PostApiFormsData = {
    /**
     * Dados de criação do formulário
     */
    body: InternalHandlerCreateFormRequest;
    path?: never;
    query?: never;
    url: '/api/forms';
};

export type PostApiFormsErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostApiFormsError = PostApiFormsErrors[keyof PostApiFormsErrors];

export type PostApiFormsResponses = {
    /**
     * Created
     */
    201: BackendInternalModelForm;
};

export type PostApiFormsResponse = PostApiFormsResponses[keyof PostApiFormsResponses];

export type DeleteApiFormsIdData = {
    body?: never;
    path: {
        /**
         * ID do Formulário
         */
        id: string;
    };
    query?: never;
    url: '/api/forms/{id}';
};

export type DeleteApiFormsIdErrors = {
    /**
     * Erro ao excluir formulário
     */
    500: string;
};

export type DeleteApiFormsIdError = DeleteApiFormsIdErrors[keyof DeleteApiFormsIdErrors];

export type DeleteApiFormsIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteApiFormsIdResponse = DeleteApiFormsIdResponses[keyof DeleteApiFormsIdResponses];

export type GetApiFormsIdData = {
    body?: never;
    path: {
        /**
         * ID do Formulário
         */
        id: string;
    };
    query?: never;
    url: '/api/forms/{id}';
};

export type GetApiFormsIdErrors = {
    /**
     * Formulário não encontrado
     */
    404: string;
};

export type GetApiFormsIdError = GetApiFormsIdErrors[keyof GetApiFormsIdErrors];

export type GetApiFormsIdResponses = {
    /**
     * OK
     */
    200: BackendInternalModelForm;
};

export type GetApiFormsIdResponse = GetApiFormsIdResponses[keyof GetApiFormsIdResponses];

export type PutApiFormsIdData = {
    /**
     * Dados atualizados do formulário
     */
    body: InternalHandlerCreateFormRequest;
    path: {
        /**
         * ID do Formulário
         */
        id: string;
    };
    query?: never;
    url: '/api/forms/{id}';
};

export type PutApiFormsIdErrors = {
    /**
     * Payload inválido
     */
    400: string;
    /**
     * Erro ao atualizar formulário
     */
    500: string;
};

export type PutApiFormsIdError = PutApiFormsIdErrors[keyof PutApiFormsIdErrors];

export type PutApiFormsIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PutApiFormsIdResponse = PutApiFormsIdResponses[keyof PutApiFormsIdResponses];

export type GetApiFormsResponsesData = {
    body?: never;
    path: {
        /**
         * ID do Formulário (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/api/forms/{id}/responses';
};

export type GetApiFormsResponsesErrors = {
    /**
     * Erro ao buscar respostas
     */
    500: string;
};

export type GetApiFormsResponsesError = GetApiFormsResponsesErrors[keyof GetApiFormsResponsesErrors];

export type GetApiFormsResponsesResponses = {
    /**
     * OK
     */
    200: Array<BackendInternalModelFormResponse>;
};

export type GetApiFormsResponsesResponse = GetApiFormsResponsesResponses[keyof GetApiFormsResponsesResponses];

export type RestoreApiFormsIdData = {
    body?: never;
    path: {
        /**
         * ID do Formulário
         */
        id: string;
    };
    query?: never;
    url: '/api/forms/{id}/restore';
};

export type RestoreApiFormsIdErrors = {
    /**
     * Erro ao restaurar formulário
     */
    500: string;
};

export type RestoreApiFormsIdError = RestoreApiFormsIdErrors[keyof RestoreApiFormsIdErrors];

export type RestoreApiFormsIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type RestoreApiFormsIdResponse = RestoreApiFormsIdResponses[keyof RestoreApiFormsIdResponses];

export type GetApiHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetApiHealthResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];

export type GetAuthGoogleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type GetAuthGoogleCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google/callback';
};

export type GetAuthGoogleCallbackErrors = {
    /**
     * Estado inválido ou Cookie ausente
     */
    400: string;
    /**
     * Falha na troca de código pelo token
     */
    500: string;
};

export type GetAuthGoogleCallbackError = GetAuthGoogleCallbackErrors[keyof GetAuthGoogleCallbackErrors];

export type PostAuthLoginData = {
    /**
     * Credenciais do usuário
     */
    body: BackendInternalModelLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Dados inválidos
     */
    400: string;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: BackendInternalModelAuthResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetPublicFormBySlugData = {
    body?: never;
    path: {
        /**
         * Slug do formulário
         */
        slug: string;
    };
    query?: never;
    url: '/f/{slug}';
};

export type GetPublicFormBySlugErrors = {
    /**
     * Formulário não encontrado ou inativo
     */
    404: string;
};

export type GetPublicFormBySlugError = GetPublicFormBySlugErrors[keyof GetPublicFormBySlugErrors];

export type GetPublicFormBySlugResponses = {
    /**
     * OK
     */
    200: BackendInternalModelForm;
};

export type GetPublicFormBySlugResponse = GetPublicFormBySlugResponses[keyof GetPublicFormBySlugResponses];

export type SubmitPublicFormData = {
    /**
     * Objeto JSON contendo as respostas
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Slug do formulário
         */
        slug: string;
    };
    query?: never;
    url: '/f/{slug}/submit';
};

export type SubmitPublicFormErrors = {
    /**
     * Payload de resposta inválido
     */
    400: string;
    /**
     * Formulário não encontrado
     */
    404: string;
    /**
     * Erro ao salvar resposta no banco
     */
    500: string;
};

export type SubmitPublicFormError = SubmitPublicFormErrors[keyof SubmitPublicFormErrors];

export type SubmitPublicFormResponses = {
    /**
     * Created
     */
    201: {
        [key: string]: string;
    };
};

export type SubmitPublicFormResponse = SubmitPublicFormResponses[keyof SubmitPublicFormResponses];
