// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/forms": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Listar Formulários",
                "operationId": "getApiAdminForms",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Exibir excluídos",
                        "name": "deleted",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/backend_internal_model.FormSummary"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar formulários",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/forms/{id}/publish": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Alternar Publicação",
                "operationId": "patchApiFormsPublish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload contendo {published: bool}",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/forms": {
            "post": {
                "description": "Cria um novo formulário com os campos especificados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Criar formulário",
                "operationId": "postApiForms",
                "parameters": [
                    {
                        "description": "Dados de criação do formulário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.CreateFormRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_model.Form"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/forms/{id}": {
            "get": {
                "description": "Retorna a estrutura completa do formulário e seus campos para edição",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Buscar Formulário por ID",
                "operationId": "getApiFormsId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_model.Form"
                        }
                    },
                    "404": {
                        "description": "Formulário não encontrado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza título, descrição, slug e reescreve os campos do formulário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Atualizar Formulário",
                "operationId": "putApiFormsId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados do formulário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.CreateFormRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Payload inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao atualizar formulário",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove o formulário e suas dependências pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Excluir Formulário",
                "operationId": "deleteApiFormsId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao excluir formulário",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/forms/{id}/responses": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Listar Respostas do Formulário",
                "operationId": "getApiFormsResponses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/backend_internal_model.FormResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar respostas",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/forms/{id}/restore": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Restaurar Formulário",
                "operationId": "restoreApiFormsId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao restaurar formulário",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Retorna OK se a aplicação estiver respondendo",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/google": {
            "get": {
                "description": "Inicia o fluxo de autenticação OAuth2 gerando o cookie de estado",
                "tags": [
                    "Auth"
                ],
                "summary": "Login com Google",
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    }
                }
            }
        },
        "/auth/google/callback": {
            "get": {
                "description": "Processa o retorno do OAuth2, valida o estado via Cookie e redireciona ao Frontend",
                "tags": [
                    "Auth"
                ],
                "summary": "Callback do Google OAuth2",
                "responses": {
                    "302": {
                        "description": "Found"
                    },
                    "400": {
                        "description": "Estado inválido ou Cookie ausente",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Falha na troca de código pelo token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Realiza autenticação simples e retorna um JWT fictício",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login com Email e Senha",
                "parameters": [
                    {
                        "description": "Credenciais do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_model.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/f/{slug}": {
            "get": {
                "description": "Retorna o formulário e seus campos visíveis usando o slug único",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "Buscar Formulário Público",
                "operationId": "getPublicFormBySlug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug do formulário",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_model.Form"
                        }
                    },
                    "404": {
                        "description": "Formulário não encontrado ou inativo",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/f/{slug}/submit": {
            "post": {
                "description": "Recebe um objeto JSON com os pares de pergunta/resposta e persiste no banco",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "Submeter Resposta de Formulário",
                "operationId": "submitPublicForm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug do formulário",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Objeto JSON contendo as respostas",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Payload de resposta inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Formulário não encontrado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao salvar resposta no banco",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "backend_internal_model.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "mock-jwt-token"
                }
            }
        },
        "backend_internal_model.Form": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_model.FormField"
                    }
                },
                "id": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "responses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_model.FormResponse"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "backend_internal_model.FormField": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "fieldType": {
                    "type": "string"
                },
                "formId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "options": {
                    "description": "@swaggertype object",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "orderIndex": {
                    "type": "integer"
                },
                "required": {
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "backend_internal_model.FormResponse": {
            "type": "object",
            "properties": {
                "answers": {
                    "description": "@swaggertype object",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "formId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "submittedAt": {
                    "type": "string"
                }
            }
        },
        "backend_internal_model.FormSummary": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "publicUrl": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "responsesCount": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "backend_internal_model.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "internal_handler.CreateFormRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_model.FormField"
                    }
                },
                "published": {
                    "type": "boolean"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Form Engine & Auth",
	Description:      "API para gerenciamento de formulários e autenticação OAuth2.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
